# Generated by Django 5.2.8 on 2025-12-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
