# Generated by Django 5.2.8 on 2025-12-18 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanandetail',
            name='pesanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='customer.pesanan'),
            preserve_default=False,
        ),
    ]
