# Generated by Django 5.2.8 on 2025-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayat',
            name='jenis',
            field=models.CharField(choices=[('pembelian', 'Pembelian'), ('top_up', 'Top Up Saldo')], default='pembelian', max_length=20),
        ),
    ]
