# Generated by Django 5.2.8 on 2025-12-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_pesanandetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanandetail',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.menuitem'),
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.IntegerField(default=0)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
