# Generated by Django 5.2.8 on 2025-12-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_pesanandetail_menu_pesanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='riwayat',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='riwayat',
            name='saldo_akhir',
        ),
        migrations.RemoveField(
            model_name='riwayat',
            name='saldo_awal',
        ),
    ]
