# Generated by Django 5.2.8 on 2025-12-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_member_created_at'),
        ('customer', '0003_riwayat_jenis'),
    ]

    operations = [
    ]
