# Generated by Django 5.2.8 on 2025-12-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama (Opsional)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Opsional)')),
                ('nomor_meja', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nomor Meja')),
                ('rating', models.IntegerField(choices=[(1, '1 Bintang'), (2, '2 Bintang'), (3, '3 Bintang'), (4, '4 Bintang'), (5, '5 Bintang')], verbose_name='Rating')),
                ('kategori', models.CharField(choices=[('pelayanan', 'Pelayanan'), ('rasa', 'Rasa Kopi'), ('suasana', 'Suasana'), ('harga', 'Harga'), ('kebersihan', 'Kebersihan'), ('lainnya', 'Lainnya')], max_length=50, verbose_name='Kategori Feedback')),
                ('komentar', models.TextField(verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Pelanggan',
                'ordering': ['-created_at'],
            },
        ),
    ]
