# Generated by Django 5.2.8 on 2025-12-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='umur',
            field=models.CharField(blank=True, choices=[('<12', 'Di bawah 12 tahun'), ('12-17', '12-17 tahun'), ('18-24', '18-24 tahun'), ('25-34', '25-34 tahun'), ('35-44', '35-44 tahun'), ('45-54', '45-54 tahun'), ('55+', '55 tahun ke atas')], max_length=10, null=True, verbose_name='Umur (Opsional)'),
        ),
    ]
