# Generated by Django 5.2.8 on 2025-12-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('stok_minimum', models.IntegerField(default=10)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kadaluarsa', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kontak', models.CharField(max_length=100)),
            ],
        ),
    ]
