# Generated by Django 5.2.8 on 2025-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Barang',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='barang',
            name='stok_minimum',
            field=models.IntegerField(),
        ),
    ]
