<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-12-04 09:26
=======
# Generated by Django 5.2.8 on 2025-12-04 07:26
>>>>>>> c1b26a62c984e5bac373fcb8b31411f47a6a7f2d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id_pegawai', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('gaji_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_jam', models.IntegerField(default=0)),
                ('jam_kerja', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pegawai_barista',
            },
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id_pegawai', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('gaji_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_jam', models.IntegerField(default=0)),
                ('jam_kerja', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pegawai_cleaner',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id_pegawai', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=100)),
                ('gaji_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jam_kerja', models.IntegerField(default=0)),
                ('jenis', models.CharField(default='pegawai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pegawai_pegawai',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id_pegawai', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('gaji_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_jam', models.IntegerField(default=0)),
                ('jam_kerja', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pegawai_waiter',
            },
        ),
    ]
