# Generated by Django 5.2.8 on 2025-12-18 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('barista', 'Barista'), ('waiter', 'Waiter'), ('cleaner', 'Cleaner')], max_length=10)),
                ('id_pegawai', models.CharField(max_length=10)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('jam_masuk', models.TimeField()),
                ('jam_pulang', models.TimeField()),
                ('jam_kerja', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('gaji_harian', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pegawai_absensi',
            },
        ),
    ]
