# Generated by Django 5.2.8 on 2025-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id_pegawai', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('gaji_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_jam', models.IntegerField(default=0)),
                ('jam_kerja', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pegawai_cleaner',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id_pegawai', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('gaji_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_per_jam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_jam', models.IntegerField(default=0)),
                ('jam_kerja', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pegawai_waiter',
            },
        ),
        migrations.RenameField(
            model_name='barista',
            old_name='bonus_per_minuman',
            new_name='bonus_per_jam',
        ),
        migrations.RenameField(
            model_name='barista',
            old_name='minuman_terjual',
            new_name='jumlah_jam',
        ),
    ]
