# Generated by Django 5.2.8 on 2025-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='gaji_harian',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_kerja',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
