# Generated by Django 5.2.8 on 2025-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_alter_absensi_gaji_harian_alter_absensi_jam_kerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='jam_lembur_malam',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='gaji_harian',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
